version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobboard_django_db
      - PGUSER=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - jobboard_django_network
  web:
    build:
      context: "./"
      dockerfile: "django.Dockerfile"
    restart: always
    container_name: web
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8085:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on: 
      db:
        condition: service_healthy
    # networks:
    #   - jobboard_django_network
volumes:
  postgres_data:
# networks:
#   jobboard_django_network:
